//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCSEvents1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JnJCompetitors
    {
        public int ParticipantID { get; set; }
        public string JnJRole { get; set; }
        public Nullable<int> WsdcNumber { get; set; }
        public string JnJDivision { get; set; }
        public int Bib { get; set; }
    
        public virtual Participant Participant { get; set; }
    }
}
