//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCSEvents1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participant()
        {
            this.JnJCompetitors = new HashSet<JnJCompetitors>();
            this.StrictlyCompetitors = new HashSet<StrictlyCompetitors>();
        }
    
        public int ParticipantID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> WsdcNumber { get; set; }
        public string PassType { get; set; }
        public string Email { get; set; }
        public string CompLevel { get; set; }
        public string WorkshopLevel { get; set; }
        public string CompRole { get; set; }
        public string WorkshopRole { get; set; }
        public string Paid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JnJCompetitors> JnJCompetitors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StrictlyCompetitors> StrictlyCompetitors { get; set; }
    }
}
