//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCSEvents1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int ParticipantID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> WsdcNumber { get; set; }
        public string PassType { get; set; }
        public string Email { get; set; }
        public string CompLevel { get; set; }
        public string WorkshopLevel { get; set; }
        public string CompRole { get; set; }
        public string WorkshopRole { get; set; }
    
        public virtual JnJCompetitors JnJCompetitors { get; set; }
        public virtual StrictlyCompetitors StrictlyCompetitors { get; set; }
    }
}
