//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCSEvents1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StrictlyCompetitors
    {
        public int ParticipantID { get; set; }
        public string StrictlyRole { get; set; }
        public string StrictlyDivision { get; set; }
        public string PartnerFirstName { get; set; }
        public string PartnerLastName { get; set; }
        public Nullable<int> PartnerID { get; set; }
    
        public virtual Participant Participant { get; set; }
    }
}
